name: Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Agent Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./agent
          push: false
          load: true
          tags: habit-wizard-agent:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build UI Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./ui
          push: false
          load: true
          tags: habit-wizard-ui:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Agent image
        run: |
          docker run --rm habit-wizard-agent:test python -c "print('Agent image built successfully')"

      - name: Test UI image
        run: |
          docker run --rm habit-wizard-ui:test python -c "print('UI image built successfully')"

      - name: Build Status
        run: |
          echo "✅ All Docker images built successfully" 